# Generated by Django 4.1.2 on 2022-10-27 10:28

import os

from django.db import migrations


def add_superuser(apps, schema_editor):
    User = apps.get_model("main", "User")
    User.objects.create_superuser("admin", password=os.environ["ADMIN_PASSWORD"])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_superuser)]
